### ISSUE TITLE
Separate out Static/Dynamic Analysis Results in Bundle?

### ISSUE THREAD

**Issue by ikiril01** [MAECProject/schemas#102]
Right now the Bundle is quite generic in terms of what it captures, which means it can capture a wide variety of analysis results, but can also make it difficult to determine the context of what these results refer to. Perhaps it would be useful to bin its child members by category, e.g. static analysis vs. dynamic analysis, for clarity?

E.g., something like:

Bundle
* Dynamic Analysis Results
    * Actions
    * Behaviors
* Static Analysis Results
    * Objects

**Comment by gtback** [comment]
I'm a bit wary of making a (somewhat-artificial) distinction between static and dynamic analysis, especially when some analysis involves information from both (e.g. comparing in-memory representation to the file on disk).

**Comment by ikiril01** [comment]
@gtback good point. It's certainly true that most types of analysis findings can result from many different types of analyses, so this is an artificial distinction.
