### ISSUE TITLE
maec_default_vocabularies.xsd "corrupted" MalwareCapabilityEnum-1.0 security degradation documentation

### ISSUE THREAD

**Issue by athiasjerome** [MAECProject/schemas#93]
check maec_default_vocabularies.xsd
in MalwareCapabilityEnum-1.0
The documentation text for "security degradation" contains "corrupted" quotes characters

**Comment by ikiril01** [comment]
Thanks for reporting this - we'll push out a fixed copy soon.

**Comment by ikiril01** [comment]
This has been fixed: http://maec.mitre.org/language/version4.1/maec_default_vocabularies.xsd
